# Data Description
- Background: 台北市YouBike2.0的交易資料以及大安區的天氣資料，用於分析台大校內YouBike的使用情況及天氣對其的影響。
- date received: 2024/03/01
- Path to data file: /datafiles
- Unit of observation: Weather -- 8784
- Sample period: 2024/03~2024/12
- Known issues:
    - 原始資料中降水量資料在雨量小於0.5mm時只會用T表示
    - 
- Definition for each variable: 
    - sno -- 站點代號
    - sna -- 站點中文名稱
    - sarea -- 站點所在區域的中文名稱
    - sareaen -- 站點所在區域的英文名稱
    - ar -- 站點地址中文名稱
    - aren -- 站點地址英文名稱
    - laititude -- 站點的緯度
    - longtitude -- 站點的經度
    - act -- 站點的禁用狀態，1表示啟用
    - total -- 站點的車位數

    - origin -- 起始站點
    - destination -- 目標站點
    - distance_km -- 兩個站點之間的距離，以公里表示
    - duration_min -- 兩個站點之間移動所需的時間，以分鐘表示
    - origin_sno -- 起始站點代號
    - destination_sno -- 目標站點代號

    - station -- 站點地址
    - date -- 在此站點借還車的日期
    - hour -- 在此站點借還車的時間
    - borrow_count -- 站點在1個小時間的借車人數
    - return_count -- 佔點個1個小時間的還車人數

    - ObsDate -- 天氣資訊的觀測日期
    - ObsTime -- 天氣資訊的觀測時間
    - StnPres -- 大安區的氣壓，單位為hPa
    - SeaPres -- 海平面氣壓，單位為hPa
    - Temperature -- 大安區的氣溫，單位為℃
    - Td dew point -- 大安區的露點溫度，單位為℃
    - RH -- 大安區的相對溼度
    - WS -- 大安區測到的風速，單位為m/s
    - WD -- 大安區的測到的風向
    - WSGust -- 最大瞬間風速，單位為m/s
    - WDGust -- 最大瞬間風風向
    - Precp -- 大安區的降水量，單位為mm，若降水量小於0.5mm則以T表示
    - PrecpHour -- 降水時數
    - GloblRad -- 大安區的全天空日射量，單位為MJ/㎡
    - UVI -- 大安區的紫外線指數

In [1]:
import pandas as pd

## Change for Your Own Data

In [2]:
ntu_area_ubike_stations = 'ntu_area_ubike_stations_sorted.csv'
routes_with_sno_clean = 'routes_with_sno_clean.csv'
station_flow_202403 = 'station_flow_202403_new.csv'
weather_data = "weather2024_3-5.csv"

## Summary

In [3]:
n_df = pd.read_csv(ntu_area_ubike_stations)
r_df = pd.read_csv(routes_with_sno_clean)
s_df = pd.read_csv(station_flow_202403)
w_df = pd.read_csv(weather_data)

### Sample

In [4]:
n_df.head(5)

,sno,sna,sarea,latitude,longitude,ar,sareaen,aren,act,total
0,500101005,YouBike2.0_辛亥復興路口西北側,大安區,25.02153,121.54299,復興南路二段368號,Daan Dist.,No. 368， Sec. 2， Fuxing S. Rd.,1,16.0
1,500101008,YouBike2.0_新生南路三段52號前,大安區,25.02112,121.53407,新生南路三段52號,Daan Dist.,No. 52， Sec. 3， Xinsheng S. Rd.,1,17.0
2,500101009,YouBike2.0_新生南路三段66號前,大安區,25.01976,121.53384,新生南路三段66號東側,Daan Dist.,No. 66， Sec. 3， Xinsheng S. Rd. (East),1,16.0
3,500101010,YouBike2.0_新生南路三段82號前,大安區,25.01894,121.53361,新生南路三段82號,Daan Dist.,No. 82， Sec. 3， Xinsheng S. Rd.,1,20.0
4,500101021,YouBike2.0_銘傳國小側門,大安區,25.01385,121.53549,羅斯福路四段21號旁天橋下,Daan Dist.,No. 21， Sec. 4， Roosevelt Rd.,1,7.0

In [5]:
r_df.head(5)

,origin,destination,distance_km,duration_min,origin_sno,destination_sno
0,YouBike2.0_辛亥復興路口西北側,YouBike2.0_新生南路三段52號前,1.143,4.3,500101005.0,500101008.0
1,YouBike2.0_辛亥復興路口西北側,YouBike2.0_新生南路三段66號前,1.296,4.8,500101005.0,500101009.0
2,YouBike2.0_辛亥復興路口西北側,YouBike2.0_新生南路三段82號前,1.390,5.1,500101005.0,500101010.0
3,YouBike2.0_辛亥復興路口西北側,YouBike2.0_銘傳國小側門,1.688,8.4,500101005.0,500101021.0
4,YouBike2.0_辛亥復興路口西北側,YouBike2.0_捷運公館站(2號出口),1.660,6.2,500101005.0,500101022.0

In [6]:
s_df.head(5)

   Unnamed: 0    station        date  hour  borrow_count  return_count
0       39957  辛亥復興路口西北側  2024-03-01     0           2.0           2.0
1       39958  辛亥復興路口西北側  2024-03-01     6           1.0           0.0
2       39959  辛亥復興路口西北側  2024-03-01     7           7.0           9.0
3       39960  辛亥復興路口西北側  2024-03-01     8          22.0          13.0
4       39961  辛亥復興路口西北側  2024-03-01     9          13.0           7.0

In [7]:
w_df.head(5)

,ObsDate,ObsTime,StnPres,SeaPres,Temperature,Td dew point,RH,WS,WD,WSGust,WDGust,Precp,PrecpHour,GloblRad,UVI
0,2024-03-01,1,1020.6,1024.3,11.0,9.8,92,1.7,100,5.9,80,0.5,0.6,0.0,0
1,2024-03-01,2,1020.4,1024.1,11.2,10.3,94,1.7,80,6.1,90,T,0.2,0.0,0
2,2024-03-01,3,1020.2,1023.9,11.2,10.4,95,1.5,110,5.6,70,T,0.7,0.0,0
3,2024-03-01,4,1020.5,1024.2,11.1,10.5,96,1.6,100,5.0,90,0.5,1.0,0.0,0
4,2024-03-01,5,1020.1,1023.8,10.8,10.0,95,1.9,100,6.7,80,0.5,0.8,0.0,0

In [ ]:
w_df[['測站氣壓(hPa)', '海平面氣壓(hPa)', '氣溫(℃)', '露點溫度(℃)', '相對溼度(%)', '風速(m/s)', '風向(360degree)', '降水時數(h)']] = w_df[['測站氣壓(hPa)', '海平面氣壓(hPa)', '氣溫(℃)', '露點溫度(℃)', '相對溼度(%)', '風速(m/s)', '風向(360degree)', '降水時數(h)']].tof

### Summary Stats

In [8]:
n_df.describe()

                sno   latitude   longitude        act      total
count  7.300000e+01  73.000000   73.000000  73.000000  73.000000
mean   5.001128e+08  25.017701  121.539003   0.986301  29.287671
std    8.538467e+03   0.002482    0.003651   0.117041  19.707922
min    5.001010e+08  25.012440  121.533340   0.000000   7.000000
25%    5.001010e+08  25.015660  121.535910   1.000000  16.000000
50%    5.001191e+08  25.017610  121.538460   1.000000  25.000000
75%    5.001191e+08  25.019760  121.541950   1.000000  40.000000
max    5.001191e+08  25.022200  121.546980   1.000000  99.000000

In [9]:
r_df.describe()

       distance_km  duration_min    origin_sno  destination_sno
count  5256.000000   5256.000000  5.256000e+03     5.256000e+03
mean      0.852166      3.104909  5.001128e+08     5.001128e+08
std       0.408031      1.547191  8.480590e+03     8.480590e+03
min       0.030000      0.100000  5.001010e+08     5.001010e+08
25%       0.543500      1.900000  5.001010e+08     5.001010e+08
50%       0.828000      3.000000  5.001191e+08     5.001191e+08
75%       1.127000      4.100000  5.001191e+08     5.001191e+08
max       2.504000      9.200000  5.001191e+08     5.001191e+08

In [10]:
s_df.describe()

         Unnamed: 0          hour  borrow_count  return_count
count  41798.000000  41798.000000  41798.000000  41798.000000
mean   20898.500000     13.069788      7.970214      7.815254
std    12066.187612      6.147693     11.784014     12.420615
min        0.000000      0.000000      0.000000      0.000000
25%    10449.250000      9.000000      1.000000      1.000000
50%    20898.500000     13.000000      4.000000      4.000000
75%    31347.750000     18.000000     10.000000     10.000000
max    41797.000000     23.000000    159.000000    203.000000

In [11]:

w_df.describe()

,ObsTime,StnPres,SeaPres,Temperature,Td dew point,RH,WS,WSGust,WDGust,PrecpHour,GloblRad,UVI
count,2208.000000,2208.000000,2208.000000,2208.000000,2208.000000,2208.000000,2208.000000,2208.000000,2208.000000,2208.000000,2208.000000,2208.000000
mean,12.500000,1010.029438,1013.567074,23.336187,19.108922,78.434783,2.046558,5.868116,157.658514,0.114538,0.560063,1.319293
std,6.923755,4.604985,4.663091,4.497562,4.749870,13.744886,1.147451,3.041298,93.276935,0.273065,0.892711,2.324774
min,1.000000,996.100000,999.600000,10.800000,-3.400000,17.000000,0.200000,1.100000,10.000000,0.000000,0.000000,0.000000
25%,6.750000,1006.700000,1010.200000,20.600000,16.600000,70.000000,1.100000,3.200000,90.000000,0.000000,0.000000,0.000000
50%,12.500000,1009.300000,1012.800000,24.000000,20.400000,81.000000,1.900000,5.400000,120.000000,0.000000,0.040000,0.000000
75%,18.250000,1012.900000,1016.425000,26.500000,22.800000,89.000000,2.900000,8.100000,210.000000,0.000000,0.792500,2.000000
max,24.000000,1023.900000,1027.600000,34.700000,26.700000,99.000000,7.400000,18.700000,360.000000,1.000000,3.720000,11.000000